id = "zed-nightfox"
name = "Nightfox Themes"
version = "0.1.1"
schema_version = 1
authors = ["ssaunderss <austinsaunders@me.com>"]
description = "Nightfox themes for Zed"
repository = "https://github.com/ssaunderss/zed-nightfox"
